// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addEntry = `-- name: AddEntry :one
INSERT INTO entries (
    id,
    user_id,
    date,
    cardio,
    cardio_type,
    plate_count,
    plank_dur,
    weight,
    waist
) VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9
)
RETURNING id, user_id, date, cardio, cardio_type, plate_count, plank_dur, weight, waist
`

type AddEntryParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Date       time.Time `json:"date"`
	Cardio     string    `json:"cardio"`
	CardioType bool      `json:"cardio_type"`
	PlateCount []int32   `json:"plate_count"`
	PlankDur   int64     `json:"plank_dur"`
	Weight     string    `json:"weight"`
	Waist      string    `json:"waist"`
}

// Add a new entry to 'entries
func (q *Queries) AddEntry(ctx context.Context, arg AddEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, addEntry,
		arg.ID,
		arg.UserID,
		arg.Date,
		arg.Cardio,
		arg.CardioType,
		pq.Array(arg.PlateCount),
		arg.PlankDur,
		arg.Weight,
		arg.Waist,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Cardio,
		&i.CardioType,
		pq.Array(&i.PlateCount),
		&i.PlankDur,
		&i.Weight,
		&i.Waist,
	)
	return i, err
}

const resetTable = `-- name: ResetTable :exec
DELETE FROM entries
`

// Delete all rows from 'entries'
func (q *Queries) ResetTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetTable)
	return err
}
