// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addGoal = `-- name: AddGoal :exec
INSERT INTO goals
(
    id,
    goal_type,
    goal_plate_count,
    goal_dur,
    goal_decimal,
    goal_number,
    goal_tier
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type AddGoalParams struct {
	ID             uuid.UUID      `json:"id"`
	GoalType       GoalTypes      `json:"goal_type"`
	GoalPlateCount []int32        `json:"goal_plate_count"`
	GoalDur        sql.NullString `json:"goal_dur"`
	GoalDecimal    sql.NullString `json:"goal_decimal"`
	GoalNumber     sql.NullInt32  `json:"goal_number"`
	GoalTier       int32          `json:"goal_tier"`
}

// Register a goal to 'goals'
func (q *Queries) AddGoal(ctx context.Context, arg AddGoalParams) error {
	_, err := q.db.ExecContext(ctx, addGoal,
		arg.ID,
		arg.GoalType,
		pq.Array(arg.GoalPlateCount),
		arg.GoalDur,
		arg.GoalDecimal,
		arg.GoalNumber,
		arg.GoalTier,
	)
	return err
}

const deleteAllGoals = `-- name: DeleteAllGoals :exec
DELETE FROM goals
`

// Remove all entries from 'goals'
func (q *Queries) DeleteAllGoals(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllGoals)
	return err
}

const getAllGoals = `-- name: GetAllGoals :many
SELECT id, goal_type, goal_plate_count, goal_dur, goal_decimal, goal_number, goal_tier FROM goals
`

// Get all goals registered in 'goals'
func (q *Queries) GetAllGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, getAllGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.GoalType,
			pq.Array(&i.GoalPlateCount),
			&i.GoalDur,
			&i.GoalDecimal,
			&i.GoalNumber,
			&i.GoalTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoalsByTier = `-- name: GetGoalsByTier :many
SELECT id, goal_type, goal_plate_count, goal_dur, goal_decimal, goal_number, goal_tier
FROM goals
WHERE goal_tier = $1
`

// Get all goals of a specified tier from 'goals'
func (q *Queries) GetGoalsByTier(ctx context.Context, goalTier int32) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, getGoalsByTier, goalTier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.GoalType,
			pq.Array(&i.GoalPlateCount),
			&i.GoalDur,
			&i.GoalDecimal,
			&i.GoalNumber,
			&i.GoalTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoalsByType = `-- name: GetGoalsByType :many
SELECT id, goal_type, goal_plate_count, goal_dur, goal_decimal, goal_number, goal_tier
FROM goals
WHERE goal_type = $1
`

// Get all registered goal of a certain type from 'goals'
func (q *Queries) GetGoalsByType(ctx context.Context, goalType GoalTypes) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, getGoalsByType, goalType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.GoalType,
			pq.Array(&i.GoalPlateCount),
			&i.GoalDur,
			&i.GoalDecimal,
			&i.GoalNumber,
			&i.GoalTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
