// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Entry struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Date       time.Time
	Cardio     string
	CardioType bool
	PlateCount []int32
	PlankDur   time.Time
	Weight     string
	Waist      string
}

type Goal struct {
	ID        uuid.UUID
	Type      string
	GoalCount []int32
	GoalDur   sql.NullTime
	GoalSpeed sql.NullString
	GoalTier  int32
}

type User struct {
	ID        uuid.UUID
	Name      string
	Height    int32
	StartDate time.Time
}

type UserGoal struct {
	ID     uuid.UUID
	UserID uuid.UUID
	GoalID uuid.UUID
}
