// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_goals.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addGoalAchievedByUser = `-- name: AddGoalAchievedByUser :one
INSERT INTO user_goals (
    id,
    user_id,
    goal_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, goal_id
`

type AddGoalAchievedByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	GoalID uuid.UUID `json:"goal_id"`
}

// Add a goal achieved by a specified user id to 'user_goals'
func (q *Queries) AddGoalAchievedByUser(ctx context.Context, arg AddGoalAchievedByUserParams) (UserGoal, error) {
	row := q.db.QueryRowContext(ctx, addGoalAchievedByUser, arg.ID, arg.UserID, arg.GoalID)
	var i UserGoal
	err := row.Scan(&i.ID, &i.UserID, &i.GoalID)
	return i, err
}

const getGoalsAchievedByUser = `-- name: GetGoalsAchievedByUser :many
SELECT id, user_id, goal_id
FROM user_goals
WHERE user_id = $1
`

// Get all the goals achieved by a specified user id from 'user_goals'
func (q *Queries) GetGoalsAchievedByUser(ctx context.Context, userID uuid.UUID) ([]UserGoal, error) {
	rows, err := q.db.QueryContext(ctx, getGoalsAchievedByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGoal
	for rows.Next() {
		var i UserGoal
		if err := rows.Scan(&i.ID, &i.UserID, &i.GoalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
