// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserById = `-- name: GetUserById :one
SELECT id, name, height, start_date FROM users
WHERE id = $1
`

// Select the specified user by UUID from 'users'
func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Height,
		&i.StartDate,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, height, start_date FROM users
WHERE name = $1
`

// Select the specified user by name for 'users'
func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Height,
		&i.StartDate,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, height, start_date FROM users
`

// Select all rows from 'users'
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Height,
			&i.StartDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newUser = `-- name: NewUser :exec
INSERT INTO users (name, height)
VALUES ($1, $2)
`

type NewUserParams struct {
	Name   string `json:"name"`
	Height int32  `json:"height"`
}

// Add a new user entry in 'users'
func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) error {
	_, err := q.db.ExecContext(ctx, newUser, arg.Name, arg.Height)
	return err
}
